language: c

sudo: required
dist: trusty

os:
  - linux
  - osx

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "SEdM6lzGSVIMv1lk4Z/kP8Hlk8lypcHrg6g/sZ/bDYhcR14uqS1wenLmKe8Cr1z7TevIM+gB4ERI9uR6jQpv45/hyVxaL5AylEk2FOcGMb/wBh8A+eq7c9s+5oxMZZvYH9C1Y1CPm38uK0pAu59XoQLL5ZiCjhbPaZ48MQZO3gGmRSAQM2DbJ02DqN9HMuIN14E0sENRtTU1IBK9oAmmOqz8fIn3I7mp07GdO5OrxgjffNT5pgKfzoahq5cPEQq/SnXczk4jk8nfUPHzayxN1NOHAyQrr+RLdKlr5Y2xiOj/+0DipNGkqXFhtBi1Dkts1JxJugvOSBJr7Llh6ePFHNsE6b1J3DaCb4ZJ5fgL2lmg0R9HDzyNMnaXIINNZLARusYwiqo1lKnovlTBNBj7EVSZ8sFNYYrurxpr0H1rFmdcAvlcKz6xd7JB2vkkl9aRT4S7jNFGIxOjwUTBFSGM0xit1eMpd2JWbm8CIB8kOSS1Ng1k4Mejj6smtZbJesYJY6CCxs+wKN911Eok9rQ+fT5mcGFO+jXMPlzqLUbL+0SYeFEP2YiqJygkQgwTvKmgez3k5I5EdDs0KqRWjiynors6nk0PRD/bWYjhXYIHfClAYiy/MZrVeVgG4zeMF4RX5ZsEnLsFfen+o+zNeC5Ooe37BYKbHbLm2xMkstuJcFg="

env:
  -
  - DISTRO=Ubuntu1804
  - DISTRO=Fedora28 CI_BUILD_TYPE=wayland
  - DISTRO=Fedora28 CI_BUILD_TYPE=misc
  - DISTRO=Fedora28 CI_BUILD_TYPE=misc-disabled
  - DISTRO=Fedora28 CI_BUILD_TYPE=release-ready
  - DISTRO=Debian91
  - DISTRO=Archlinux

services:
  - docker

matrix:
  fast_finish: true
  exclude:
    - os: osx
      env: DISTRO=Ubuntu1804
    - os: osx
      env: DISTRO=Fedora28 CI_BUILD_TYPE=wayland
    - os: osx
      env: DISTRO=Fedora28 CI_BUILD_TYPE=misc
    - os: osx
      env: DISTRO=Fedora28 CI_BUILD_TYPE=misc-disabled
    - os: osx
      env: DISTRO=Fedora28 CI_BUILD_TYPE=release-ready
    - os: osx
      env: DISTRO=Debian91
    - os: osx
      env: DISTRO=Archlinux

  allow_failures:
    - os: linux
      env:
    - os: linux
      env: DISTRO=Fedora28 CI_BUILD_TYPE=release-ready

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$DISTRO" == "" ]]; then echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca- ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then .ci/ci-osx-deps.sh ; fi

before_script:
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$DISTRO" != "" ]]; then
        docker pull stefanschmidt1/ci-support-files:$DISTRO
      fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$DISTRO" == "" ]]; then .ci/ci-linux-deps-ubuntu1404.sh ; fi
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$DISTRO" != "" ]]; then
        docker run -v `pwd`:/src -w /src stefanschmidt1/ci-support-files:$DISTRO /src/.ci/ci-linux-build.sh $CI_BUILD_TYPE
      fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then .ci/ci-osx-build.sh ; fi

after_success:
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$DISTRO" != "" ]]; then
        docker login -u stefanschmidt1 -p "$DOCKER_PASSWORD"
        docker tag stefanschmidt1/ci-support-files:$DISTRO stefanschmidt1/ci-support-files:$DISTRO-$TRAVIS_BUILD_NUMBER
        docker push stefanschmidt1/ci-support-files:$DISTRO
        docker push stefanschmidt1/ci-support-files:$DISTRO-$TRAVIS_BUILD_NUMBER
      fi

addons:
  apt:
    update: true
  coverity_scan:
    project:
      name: "Enlightenment/efl"
      description: "Build submitted via Travis CI"
    notification_email: stefan@datenfreihafen.org
    build_command_prepend: "./autogen.sh --disable-systemd && ./configure && make clean"
    build_command: "make -j 10"
    branch_pattern: devs\/stefan\/travis-reliable-ci

notifications:
  irc:
    channels:
      - "chat.freenode.net#edevelop"
    on_success: change
    on_failure: always
    template:
      - "TravisCI build %{build_number} in branch %{branch}: %{result} - %{message}"
      - "Commit: %{commit_subject} (%{commit}) from %{author}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"

